### ISSUE TITLE
Changes In UI

### ISSUE THREAD

**Issue by hithere-devs** [Utkarsh-88034/saddweb-ecom#1]
Keep all widths either 100% or don't set them and keep a max width for larger screen sizes as the screen does not expand more in larger screen sizes. Specially in  Home Page

**Comment by Utkarsh-88034** [comment]
> Keep all widths either 100% or don't set them and keep a max width for larger screen sizes as the screen does not expand more in larger screen sizes. Specially in Home Page

Design has all widths at 80% of screen size, is it not getting that larger in large screens even then? because is have set all widths to 80% of screen size and there children have 100% width. No width has been set to be fixed.
can you send a screen shot
